uboot_env: fix compilation for glibc version >= 2.28
Starting with glibc 2.28, include file sys/stat.h will have a
definition for struct statx, in which case include file linux/stat.h should be
avoided, in order to prevent a duplicate definition.

This commit fixes (if _GNU_SOURCE is defined):

/usr/include/linux/stat.h:56:8: error: redefinition of ‘struct statx_timestamp’
 struct statx_timestamp {
        ^~~~~~~~~~~~~~~

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>